apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 40.3.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system

  values:
    grafana:
      enabled: false
      defaultDashboardsTimezone: "${TIMEZONE}"
      forceDeployDatasources: true
      forceDeployDashboards: true

    nodeExporter:
      # we install prometheus-node-exporter on host system
      enabled: false

