apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  interval: 60m
  timeout: 15m
  retryInterval: 30s
  dependsOn:
    - name: longhorn-storage
  path: "./kubernetes/core/storage/docker-registry/operator"
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: docker-registry
    namespace: storage

