apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfgmap

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nzbget
  namespace: vpn-apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: traefik
    namespace: networking
  - name: longhorn
    namespace: storage

  values:
    global:
      nameOverride: *app

    image:
      repository: ghcr.io/linuxserver/nzbget
      tag: latest

    strategy:
      type: Recreate

    env:
      TZ: "${TIMEZONE}"
      UMASK: "000"
      NZBGET_USER: "root"
      NZBGET_PASS: "${SECRET_WEBSERVICES_PASSWORD}"

    service:
      main:
        ports:
          http:
            port: 6789

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "nzbget.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    configmap:
      scripts:
        enabled: true
        data:
          GetPw.py: |
            #!/usr/bin/python3
            ##############################################################################
            ### NZBGET SCAN SCRIPT                                     ###
            #
            # Scans filename of incoming NZBs for embedded passwords.
            #
            ##############################################################################
            ### OPTIONS                                                                ###
            # The RegEx to match the password in the filename.
            #regex=(.*)\{\{(.*)\}\}.nzb

            ### NZBGET SCAN SCRIPT                                     ###
            ##############################################################################

            import re
            import getopt
            import sys
            import os

            nzbfile = os.environ.get('NZBNP_NZBNAME')
            regex = os.environ.get('NZBPO_REGEX')

            if nzbfile:
              pattern = re.compile(regex)
              match = pattern.search(nzbfile)
              password = ""
              name = nzbfile
              if match:
                name = match.group(1)
                password = match.group(2)

              print("[NZB] NZBNAME=" + name)
              if password:
                print("[NZB] NZBPR_*Unpack:Password=" + password)

    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 512Mi
        mountPath: /config
      downloads:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 64Gi
        mountPath: /downloads
      scripts:
        enabled: true
        type: configMap
        mountPath: /downloads/scripts
        name: nzbget-scripts
