apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &db planer-postgresql
  namespace: apps
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: 12.2.7
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system



  values:
    fullnameOverride: *db
    auth:
      postgresPassword: ${SECRET_WEBSERVICES_PASSWORD}

    primary:
      persistence:
        enabled: true
        existingClaim: planer-db

    resources:
      requests:
        cpu: 25m
        memory: 128M
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app planer-webui
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: planer-postgresql
    namespace: apps

  values:
    global:
      nameOverride: *app

    image:
      repository: ghcr.io/niki-on-github/serien-and-movie-planer
      tag: v0.2.0

    service:
      main:
        ports:
          http:
            port: 8888

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "planer.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    env:
      TZ: "${TIMEZONE}"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "myrandomsecret"
      POSTGRES_DB: "serien_and_movie_planer"
      POSTGRES_HOST: "planer-postgresql.apps.svc.cluster.local"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &crawler planer-crawler
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system


  dependsOn:
  - name: planer-postgresql
    namespace: apps

  values:
    global:
      nameOverride: *crawler

    image:
      repository: ghcr.io/niki-on-github/serien-and-movie-crawler
      tag: v0.2.0

    service:
      main:
        enabled: false

    env:
      TZ: "${TIMEZONE}"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "myrandomsecret"
      POSTGRES_DB: "serien_and_movie_planer"
      POSTGRES_HOST: "planer-postgresql.apps.svc.cluster.local"
