---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-custom-path
  namespace: storage
data:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/run/wrappers/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
---
# see: https://github.com/longhorn/longhorn/issues/2166#issuecomment-1293268590
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-host-path-to-longhorn
  annotations:
    policies.kyverno.io/title: Add Environment Variables from ConfigMap
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/category: Other
    policies.kyverno.io/description: >-
      Longhorn invokes executables on the host system, and needs
      to be aware of the host systems PATH. This modifies all
      deployments such that the PATH is explicitly set to support
      NixOS based systems.
spec:
  rules:
    - name: add-env-vars
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - storage
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - (name): "*"
                envFrom:
                  - configMapRef:
                      name: longhorn-custom-path
            containers:
              - (name): "*"
                envFrom:
                  - configMapRef:
                      name: longhorn-custom-path
---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-minio-secret
  namespace: storage
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${SECRET_MINIO_ACCESS_KEY_BASE64}
  AWS_SECRET_ACCESS_KEY: ${SECRET_MINIO_SECRET_KEY_BASE64}
  # echo -n http://minio.backup.svc.cluster.local | base64
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLmJhY2t1cC5zdmMuY2x1c3Rlci5sb2NhbA==
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 1h

  install:
    remediation:
      retries: -1

  upgrade:
    remediation:
      retries: 5

  values:
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      host: "lh.${SECRET_DOMAIN}"
      tls: true

    enablePSP: false

    defaultSettings:
      backupTarget: "s3://longhorn@local/"
      backupTargetCredentialSecret: longhorn-backup-minio-secret
      defaultDataPath: "${LONGHORN_DATA_PATH}"
      defaultReplicaCount: 1
      allowVolumeCreationWithDegradedAvailability: true
      disableSchedulingOnCordonedNode: false
      orphanAutoDeletion: true

