---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{ .PROJECT_DIR }}/kubernetes"
  REPO_URL:
    sh: "git config --get remote.origin.url"

includes:
  cluster: .taskfiles/cluster.yml
