apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2022.8.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: traefik
      namespace: ingress
    - name: longhorn
      namespace: storage

  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: &host "auth.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
        # - host: "*.${SECRET_DOMAIN}"
        #   paths:
        #     - path: /outpost.goauthentik.io/
        #       pathType: Prefix
      tls:
        - hosts:
            - *host

    authentik:
      secret_key: "${SECRET_AUTHENTIK_SECRET_KEY}"
      log_level: debug

      postgresql:
        password: "${SECRET_WEBSERVICES_PASSWORD}"
        # host: '{{ .Release.Name }}-postgresql-0'

      # redis:
        # host: '{{ .Release.Name }}-redis-master-0'

    postgresql:
      enabled: true
      fullnameOverride: authentik-postgresql
      postgresqlPassword: "${SECRET_WEBSERVICES_PASSWORD}"
      persistence:
        enabled: true
        storageClass: longhorn

    redis:
      enabled: true
      # fullnameOverride: authentik-redis
      master:
        persistence:
          enabled: false

