---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app webdav
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    remediation:
      retries: -1

  upgrade:
    remediation:
      retries: 5

  values:
    global:
      nameOverride: *app

    image:
      repository: bytemark/webdav
      tag: "2.4"

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "webdav.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: webdav-data
        mountPath: /var/lib/dav

    env:
      TZ: "${TIMEZONE}"
      AUTH_TYPE: "Basic"
      USERNAME: "webdav"
      PASSWORD: "${SECRET_WEBSERVICES_PASSWORD}"

