apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: thanos
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 2m0s
  timeout: 15m
  dependsOn:
    - name: longhorn-storage
    - name: minio
    - name: traefik
  path: "./kubernetes/core/monitoring/thanos/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

