apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.7.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system

  values:
    # required to get thanos discovery working
    fullnameOverride: prometheus

    grafana:
      enabled: false
      defaultDashboardsTimezone: "${TIMEZONE}"
      forceDeployDatasources: false
      forceDeployDashboards: true

    nodeExporter:
      # we install prometheus-node-exporter on host system
      enabled: false

    prometheus:
      prometheusSpec:
        replicas: 1
        replicaExternalLabelName: "replica"
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        retention: 6h
        enableAdminAPI: true
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              selector:
                matchLabels:
                  app.kubernetes.io/name: prometheus
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
        thanos:
          objectStorageConfig:
            name: thanos-objstore-config
            key: objstore.yml

        resources:
          requests:
            cpu: 50m
            memory: 128M

      thanosService:
        enabled: true

      thanosServiceMonitor:
        enabled: true


