apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: whoami
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 2m0s
  timeout: 15m
  dependsOn:
    - name: traefik
  path: "./kubernetes/core/networking/whoami/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

