---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5

  values:
    fullnameOverride: *app

    config:
      devices:
        - /dev/sda
        - /dev/sdb
        - /dev/sdc
        - /dev/nvme0n1
        - /dev/nvme0n2

    prometheusRules:
      enabled: false
