---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: kube-system
  annotations:
    meta.helm.sh/release-namespace: "kube-system"
spec:
  interval: 1h
  chart:
    spec:
      chart: manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio-source
        namespace: flux-system
  values:
    operatorNamespace: istio-operator
    istioNamespace: istio-system
