---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 60m
  chart:
    spec:
      chart: goldilocks
      version: 6.4.0
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system

  # https://github.com/FairwindsOps/charts/blob/master/stable/goldilocks/values.yaml
  values:
    vpa:
      enabled: true

    dashboard:
      replicaCount: 1

      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
