---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_PODS_NETWORK_IP_POOL: "10.42.0.0/16"
  CLUSTER_SERVICE_NETWORK_IP_POOL: "10.43.0.0/16"
  GATEWAY_IP: "10.0.1.1"
  LONGHORN_DATA_PATH: "/var/lib/longhorn"
  NFS_BACKUP_SERVER: "10.0.1.200"
  SVC_GITEA_SSH_IP: "10.0.1.200"
  TIMEZONE: "Europe/Berlin"

