---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: istio-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/istio/istio.git
  ref:
    # renovate: datasource=github-releases depName=istio/istio
    tag: 1.16.1
  ignore: |
    # exclude all
    /*
    # path to operator
    !/manifests/charts/istio-operator

