---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: istio-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/istio/istio.git
  ref:
    tag: 1.14.3
  ignore: |
    # exclude all
    /*
    # path to operator
    !/manifests/charts/istio-operator

