- name: "Setup ssh-agent for user {{ username }}"
  when: ansible_facts['distribution'] != "NixOS"
  block:

  - name: "Set SSH_AUTH_SOCK"
    lineinfile:
      path: "/home/{{ username }}/.pam_environment"
      line: 'SSH_AUTH_SOCK DEFAULT="${XDG_RUNTIME_DIR}/ssh-agent.socket"'
      create: true

  - name: 'Create ssh-agent service directory'
    file:
      dest: "{{ item }}"
      state: directory
      owner: "{{ username }}"
      recurse: no
    with_items:
       - "/home/{{ username }}/.config"
       - "/home/{{ username }}/.config/systemd"
       - "/home/{{ username }}/.config/systemd/user"
       - "/home/{{ username }}/.config/systemd/user/default.target.wants"

  - name: "Copy ssh-agent service file"
    copy:
      src: "files/ssh-agent.service"
      dest: "/home/{{ username }}/.config/systemd/user/ssh-agent.service"

  - name: 'Enable ssh-agent systemd service'
    systemd:
      name: 'ssh-agent'
      state: 'started'
      enabled: 'yes'
      scope: 'user'
