apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &db wikijs-postgresql
  namespace: apps
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: 12.3.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system

  values:
    fullnameOverride: *db
    auth:
      postgresPassword: ${SECRET_WEBSERVICES_PASSWORD}
      database: "wikijs"

    primary:
      persistence:
        enabled: true
        existingClaim: wikijs-db

    resources:
      requests:
        cpu: 25m
        memory: 128M
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wikijs
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: wikijs-postgresql
    namespace: apps

  values:
    global:
      nameOverride: *app

    image:
      # renovate: datasource=docker
      repository: ghcr.io/requarks/wiki
      tag: 2.5.298

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "wiki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    env:
      DB_PORT: 5432
      DB_HOST: wikijs-postgresql
      DB_TYPE: postgres
      DB_PASS: "${SECRET_WEBSERVICES_PASSWORD}"
      DB_NAME: "wikijs"
      DB_USER: "postgres"
