---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: minio-crd-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/minio/operator.git
  ref:
    tag: v4.5.2
  ignore: |
    # exclude all
    /*
    # path to crds
    !/resources/base/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: true
  sourceRef:
    kind: GitRepository
    name: minio-crd-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tenants.minio.min.io
  #TODO patch does not work
  # patches:
  #   - patch: |-
  #       - op: remove
  #         path: /meta/annotations
  #     target:
  #       group: minio.min.io
  #       kind: CustomResourceDefinition
  #   - patch: |-
  #       - op: remove
  #         path: /meta/labels
  #     target:
  #       group: minio.min.io
  #       kind: CustomResourceDefinition

