apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-vyos
  namespace: kubevirt
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
        machine:
          type: ""
        resources:
          requests:
            memory: 2048M
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: vm-vyos-dv
        name: datavolumedisk1
      - vyos_userdata:
          userData: |-
            #cloud-config
            vyos_config_commands:
              - set system host-name 'vyos'
              - set system ntp server 1.de.pool.ntp.org

        name: vyosuserdatadisk
  dataVolumeTemplates:
  - metadata:
      name: vm-vyos-dv
    spec:
      pvc:
        storageClassName: longhorn
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 16Gi
      source:
        http:
          url: https://github.com/niki-on-github/vyos-qemu-images/releases/download/main/vyos-1.4-rolling-202211010829-cloud-init-10G-qemu.qcow2
