apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-storage
  namespace: flux-system
spec:
  interval: 60m
  timeout: 15m
  retryInterval: 30s
  dependsOn:
    - name: longhorn
  path: "./cluster/core/storage/longhorn/storage"
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: longhorn-ui
    namespace: storage
  - apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-manager
    namespace: storage
  - apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-csi-plugin
    namespace: storage
