apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 2m0s
  timeout: 5m
  path: "./kubernetes/core/networking/authentik/operator"
  prune: true
  dependsOn:
    - name: longhorn-storage
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: authentik-server
    namespace: networking


