---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 2m
  timeout: 20m
  retryInterval: 30s
  dependsOn:
  - name: flux-system
  - name: config
  path: ./kubernetes/core
  prune: true
  force: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  healthChecks:
  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    name: traefik
    namespace: flux-system
  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    name: longhorn
    namespace: flux-system
  - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    name: longhorn-storage
    namespace: flux-system
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
              - kind: Secret
                name: cluster-secrets
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1beta2
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
