---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - settings/cluster.yaml
  - secrets/ca-certs.sops.yaml
  - secrets/cluster-secrets.sops.yaml
  - secrets/vpn-config.sops.yaml
configMapGenerator:
- name: longhorn-volumes-config
  namespace: storage
  files:
  - settings/volumes.yaml
  options:
    disableNameSuffixHash: true
    labels:
      type: generated
