apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 11.1.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system

  dependsOn:
    - name: traefik
      namespace: networking
    - name: longhorn
      namespace: storage
    - name: minio-operator
      namespace: minio-operator

  values:
    query:
      enabled: true
      replicaCount: 1
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: &host "thanos.${SECRET_DOMAIN}"
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        tls: true
        extraTls:
          - hosts:
              - *host

    queryFrontend:
      enabled: false

    bucketweb:
      enabled: true

    compactor:
      enabled: true
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 180d
      persistence:
        enabled: false

    storegateway:
      enabled: true
      replicaCount: 1
      podAntiAffinityPreset: hard
      persistence:
        enabled: true
        storageClass: longhorn
        size: 5Gi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    existingObjstoreSecret: thanos-objstore-config

