---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: apps
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: traefik
    namespace: networking
  - name: longhorn
    namespace: storage

  values:
    image:
      # renovate: datasource=docker
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.11.3

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"

    env:
      COMPOSE_PROJECT_NAME: paperless
      PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless/consume
      PAPERLESS_CONSUMER_POLLING: "60"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
      PAPERLESS_OCR_LANGUAGES: "deu eng"
      PAPERLESS_OCR_LANGUAGE: "deu"
      PAPERLESS_PORT: 8000
      PAPERLESS_REDIS: redis://paperless-redis.apps.svc.cluster.local:6379
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_TIME_ZONE: "${TIMEZONE}"
      PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
      USERMAP_GID: 0
      USERMAP_UID: 0
      PAPERLESS_ADMIN_USER: "root"
      PAPERLESS_ADMIN_PASSWORD: "${SECRET_WEBSERVICES_PASSWORD}"
      PAPERLESS_ADMIN_MAIL: "root@${SECRET_DOMAIN}"

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        mountPath: /usr/src/paperless/data
        type: pvc
        existingClaim: paperless-data
      media:
        enabled: true
        mountPath: /usr/src/paperless/media
        type: pvc
        existingClaim: paperless-media
      consume:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: nfs-storage
        size: 8Gi
        mountPath: /usr/src/paperless/consume
      export:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: nfs-storage
        size: 128Gi
        mountPath: /usr/src/paperless/export

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    image:
      # renovate: datasource=docker
      repository: docker.io/library/redis
      tag: 7.0.8

    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379

