apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/ks.yaml
  - loki-stack/ks.yaml
  - metrics-server
  - prometheus-stack/ks.yaml
  - scrutiny/ks.yaml
  - smarctl-exporter
  - thanos/ks.yaml
  - uptime-kuma/ks.yaml
