---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
  - name: crds
  - name: namespaces
  path: ./cluster/charts
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
