---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 1m
  timeout: 15m
  retryInterval: 30s
  dependsOn:
  - name: namespaces
  path: ./cluster/charts
  prune: true
  force: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
