---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
  - name: namespaces
  path: ./cluster/crds
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
