---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - helm-release.yaml
  - default-tls-store.yaml
  - midleware-rfc1918.yaml
  - dashboard.yaml
