apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  BACKUP_STORAGE_AFFINITY_HOSTNAME: "server1"
  CLUSTER_PODS_NETWORK_IP_POOL: "10.42.0.0/16"
  CLUSTER_SERVICE_NETWORK_IP_POOL: "10.43.0.0/16"
  GATEWAY_IP: "10.0.1.1"
  HOST_NETWORK_IP: "10.0.1.0"
  LONGHORN_DATA_PATH: "/opt/k3s/longhorn"
  MINIO_BACKUP_STORAGE_HOST_PATH: "/mnt/backup/k3s/minio"
  NETBOOT_SERVER_AFFINITY_HOSTNAME: "server1"
  NFS_SERVER_AFFINITY_HOSTNAME: "server1"
  NFS_STORAGE_PROVISIONER_HOST_PATH: "/opt/k3s/data"
  SAMBA_HOST_PATH: "/opt/k3s/data"
  SAMBA_SERVER_AFFINITY_HOSTNAME: "server1"
  SVC_GITEA_SSH_IP: "10.0.1.200"
  SVC_NETBOOT_IP: "10.0.1.200"
  SVC_NFS_IP: "10.0.1.200"
  SVC_SAMBA_IP: "10.0.1.200"
  TIMEZONE: "Europe/Berlin"

