---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app syncthing
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 1h

  values:
    global:
      nameOverride: *app

    image:
      repository: syncthing/syncthing
      tag: 1.21.0

    service:
      main:
        ports:
          http:
            port: 8384
      listdisc:
        enabled: true
        type: LoadBalancer
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
          listen:
            enabled: true
            port: 22000
            protocol: TCP

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "sync.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        mountPath: /var/syncthing
        accessMode: ReadWriteOnce
        storageClass: longhorn
        type: pvc
        size: 32Gi

    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        memory: 300Mi

    env:
      PUID: "1000"
      PGID: "1000"
