---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app netboot
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    global:
      nameOverride: *app

    image:
      repository: ghcr.io/niki-on-github/netboot-xyz
      tag: v1.0.2

    service:
      main:
        enabled: false

    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
      privileged: true

    env:
      NETWORK_IP: "${HOST_NETWORK_IP}"

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - "${NETBOOT_SERVER_AFFINITY_HOSTNAME}"
