apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  timeout: 20m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: longhorn
    namespace: storage

  values:
    global:
      nameOverride: *app

    image:
      repository: louislam/uptime-kuma
      tag: 1.19.6

    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        mountPath: /app/data
        type: pvc
        existingClaim: uptime-kuma-config
