apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jdownloader
  namespace: vpn-apps
  annotations:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "jdownloader"
    meta.helm.sh/release-namespace: "vpn-apps"
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    global:
      nameOverride: *app

    image:
      repository: jlesage/jdownloader-2
      tag: v23.03.1

    strategy:
      type: Recreate

    env:
      TZ: "${TIMEZONE}"
      UMASK: "000"

    service:
      main:
        ports:
          http:
            port: 5800

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "jdownloader.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: jdownloader-config
        mountPath: /config
      downloads:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: nfs-storage
        size: 512Gi
        mountPath: /output

