---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: traefik
    namespace: networking
  - name: longhorn
    namespace: storage

  values:
    image:
      repository: vaultwarden/server
      tag: 1.25.2

    strategy:
      type: Recreate

    # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
    env:
      DATA_FOLDER: "config"
      DOMAIN: "https://vaultwarden.${SECRET_DOMAIN}"
      WEBSOCKET_ENABLED: true
      INVITATIONS_ALLOWED: false
      ADMIN_TOKEN: "${SECRET_WEBSERVICES_PASSWORD}"
      TZ: "${TIMEZONE}"

    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "vaultwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 4Gi
        mountPath: /config
