apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-pvc-samba-share
  namespace: storage
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 1800
  template:
    spec:
      serviceAccountName: longhorn-pvc-samba-share
      containers:
      - name: longhorn-pvc-samba-share
        imagePullPolicy: Always
        image: ghcr.io/niki-on-github/longhorn-pvc-samba-share:v1.0.0
        env:
        - name: NAMESPACE
          value: "apps"
        - name: START_DELAY_IN_SECONDS
          value: "1"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ADDITIONAL_HOST_VOLUME_PATHS
          value: "${SAMBA_HOST_PATH}"
        - name: AFFINITY_HOSTNAME
          value: "${SAMBA_SERVER_AFFINITY_HOSTNAME}"
        - name: SVC_SAMBA_IP
          value: "${SVC_SAMBA_IP}"
        - name: SAMBA_PASSWORD
          value: "${SECRET_WEBSERVICES_PASSWORD}"
        volumeMounts:
        - name: longhorn-volumes-config
          mountPath: /config/volumes.yaml
          subPath: volumes.yaml
      restartPolicy: Never
      volumes:
      - name: longhorn-volumes-config
        configMap:
          name: longhorn-volumes-config
