---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: storage
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: longhorn
    namespace: storage

  values:
    image:
      repository: registry
      tag: "2"

    strategy:
      type: Recreate

    service:
      main:
        ports:
          http:
            enabled: false
          registry:
            enabled: true
            port: 5000
            protocol: TCP

    ingress:
      registry:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "docker-registry.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /var/lib/registry
        existingClaim: docker-registry

    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          httpGet:
            path: /v2
            port: 5000
