---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: apps
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 6.0.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system

  dependsOn:
  - name: traefik
    namespace: networking
  - name: longhorn
    namespace: storage

  values:
    replicaCount: 1

    service:
      ssh:
        type: LoadBalancer
        port: 222
        externalTrafficPolicy: Local
        loadBalancerIP: "${SVC_GITEA_SSH_IP}"
      http:
        port: 3000

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: &host "git.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    persistence:
      enabled: true
      storageClass: longhorn

    gitea:
      admin:
        email: "root@${SECRET_DOMAIN}"
        username: root
        password: "${SECRET_WEBSERVICES_PASSWORD}"
      security:
        SECRET_KEY: "${SECRET_GITEA_SECRET}"
      config:
        APP_NAME: "Gitea"
        server:
          PROTOCOL: http
          DOMAIN: "git.${SECRET_DOMAIN}"
          ROOT_URL: "https://git.${SECRET_DOMAIN}"
          SSH_PORT: 222
          SSH_LISTEN_PORT: 222
          SSH_DOMAIN: "git.${SECRET_DOMAIN}"
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
        webhook:
          ALLOWED_HOST_LIST: "*"
          SKIP_TLS_VERIFY: true

    postgresql:
      enabled: true
      persistence:
        enabled: true
        storageClass: longhorn

    memcached:
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 256M
