apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 2m0s
  timeout: 5m
  path: "./kubernetes/core/storage/minio/operator"
  prune: true
  dependsOn:
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: tenants.minio.min.io

