apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &db homeassistant-postgresql
  namespace: apps
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: 11.9.0
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system

  dependsOn:
  - name: longhorn
    namespace: storage

  values:
    fullnameOverride: *db
    auth:
      postgresPassword: ${SECRET_WEBSERVICES_PASSWORD}

    persistence:
      enabled: true
      storageClass: longhorn

    resources:
      requests:
        cpu: 25m
        memory: 128M
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homeassistant
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: homeassistant-postgresql
    namespace: apps
  - name: longhorn
    namespace: storage
  - name: traefik
    namespace: networking
  - name: homeassistant-postgresql
    namespace: apps

  values:
    global:
      nameOverride: *app

    image:
      repository: homeassistant/home-assistant
      tag: 2022.9.7

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        storageClass: longhorn
        type: pvc
        size: 32Gi

    env:
      postgresql_uri: "postgres://postgres:${SECRET_WEBSERVICES_PASSWORD}@homeassistant-postgresql.apps.svc/postgres?sslmode=disable"
