---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 2m0s
  timeout: 15m
  path: "./kubernetes/core/storage/longhorn/operator"
  prune: true
  wait: true
  force: true
  dependsOn:
    - name: kyverno-operator
    - name: minio-local-storage
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: longhorn-ui
    namespace: storage
  - apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-manager
    namespace: storage
  - apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-csi-plugin
    namespace: storage
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-backup
  namespace: flux-system
spec:
  interval: 60m
  timeout: 15m
  retryInterval: 0m30s
  dependsOn:
    - name: longhorn
  path: "./kubernetes/core/storage/longhorn/backup"
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-storage
  namespace: flux-system
spec:
  interval: 60m
  timeout: 15m
  retryInterval: 30s
  dependsOn:
    - name: longhorn
    - name: longhorn-backup
  path: "./kubernetes/core/storage/longhorn/storage"
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: longhorn-ui
    namespace: storage
  - apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-manager
    namespace: storage
  - apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-csi-plugin
    namespace: storage
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-samba-server
  namespace: flux-system
spec:
  interval: 60m
  timeout: 15m
  retryInterval: 30s
  dependsOn:
    - name: longhorn
    - name: longhorn-storage
  path: "./kubernetes/core/storage/longhorn/samba-server"
  prune: true
  wait: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
