---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: volsync
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 2m0s
  timeout: 15m
  path: "./kubernetes/core/backup/volsync/operator"
  prune: true
  wait: true
  force: true
  dependsOn:
    - name: external-snapshotter
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: kyverno
    namespace: policy
