---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: apps
spec:
  interval: 1h
  chart:
    spec:
      chart: gitea
      version: 8.1.0
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system

  values:
    replicaCount: 1

    service:
      ssh:
        type: LoadBalancer
        port: 222
        externalTrafficPolicy: Local
        loadBalancerIP: "${SVC_GITEA_SSH_IP}"
      http:
        port: 3000

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: &host "git.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    persistence:
      enabled: true
      existingClaim: gitea-data

    gitea:
      admin:
        email: "root@${SECRET_DOMAIN}"
        username: root
        password: "${SECRET_WEBSERVICES_PASSWORD}"
      security:
        SECRET_KEY: "${SECRET_GITEA_SECRET}"
      config:
        APP_NAME: "Gitea"
        server:
          PROTOCOL: http
          DOMAIN: "git.${SECRET_DOMAIN}"
          ROOT_URL: "https://git.${SECRET_DOMAIN}"
          SSH_PORT: 222
          SSH_LISTEN_PORT: 222
          SSH_DOMAIN: "git.${SECRET_DOMAIN}"
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
        webhook:
          ALLOWED_HOST_LIST: "*"
          SKIP_TLS_VERIFY: true
        metrics:
          ENABLED: true
        api:
          ENABLE_SWAGGER: true
        packages:
          ENABLED: true
        actions:
          ENABLED: true

    postgresql:
      enabled: true
      persistence:
        enabled: true
        # the name can not set since chart version 8, below name is the default one
        existingClaim: data-gitea-postgresql-0

    memcached:
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 256M
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app gitea-runner
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    image:
      # TODO change me if official image is availabe from gitea
      repository: vegardit/gitea-act-runner
      tag: "latest"

    global:
      nameOverride: *app

    env:
      TZ: "${TIMEZONE}"
      GITEA_INSTANCE_URL: "https://git.${SECRET_DOMAIN}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${SECRET_GITEA_RUNNER_TOKEN}"
      GITEA_INSTANCE_INSECURE: true
      GITEA_RUNNER_JOB_CONTAINER_OPTIONS: "--add-host=git.${SECRET_DOMAIN}:host-gateway -e GIT_SSL_NO_VERIFY=true -e RUNNER_TEMP=/tmp"

    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false

    persistence:
      docker-sock:
        enabled: true
        type: hostPath
        mountPath: "/var/run/docker.sock"
        hostPath: "/var/run/docker.sock"
      data:
        enabled: true
        type: pvc
        mountPath: /data
        existingClaim: gitea-runner-data
