---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  dependsOn:
  - name: traefik
    namespace: ingress

  values:
    image:
      repository: traefik/traefikee-webapp-demo
      tag: v2

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: "ingress-auth@kubernetescrd"
        hosts:
          - host: &host "whoami.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
