apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 2m0s
  timeout: 5m
  path: "./cluster/core/networking/authentik/operator"
  prune: true
  dependsOn:
    - name: longhorn-storage
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: authentik-server
    namespace: networking


