---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.10.0/crd.yaml
  - system-upgrade-controller
