apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.40.0
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system

  values:
    nameOverride: *app

    service:
      portName: http
      port: 3000

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - "grafana.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "grafana.${SECRET_DOMAIN}"

    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 200Mi

    adminUser: root
    adminPassword: "${SECRET_WEBSERVICES_PASSWORD}"

    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL

      datasources:
        enabled: true
        searchNamespace: ALL

    plugins:
      - grafana-piechart-panel
      - grafana-worldmap-panel
      - grafana-clock-panel

    serviceMonitor:
      enabled: true

    persistence:
      enabled: false
